version: '3.9'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: kustay_db
      POSTGRES_USER: kustay_user
      POSTGRES_PASSWORD: kustay_password
    ports:
        - "5433:5432"   # host:container
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata:
