# Generated by Django 5.2.7 on 2025-10-29 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kustay", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_min",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "budget_max",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("move_in_date", models.DateField(blank=True, null=True)),
                ("smoker", models.BooleanField(default=False)),
                ("pets", models.BooleanField(default=False)),
                (
                    "sleep_schedule",
                    models.CharField(
                        choices=[
                            ("early_bird", "Early Bird"),
                            ("night_owl", "Night Owl"),
                            ("flexible", "Flexible"),
                        ],
                        default="flexible",
                        max_length=20,
                    ),
                ),
                (
                    "cleanliness_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("lifestyle_notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="kustay.user",
                    ),
                ),
            ],
        ),
    ]
