# Generated by Django 5.2.7 on 2025-10-30 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("kustay", "0003_alter_profile_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "listing_id",
                    models.BigAutoField(
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "listing_type",
                    models.CharField(
                        choices=[
                            ("apartment", "Apartment"),
                            ("house", "House"),
                            ("condo", "Condo"),
                            ("room", "Room"),
                        ],
                        default="apartment",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("neighborhood", models.CharField(blank=True, max_length=120)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                    ),
                ),
                ("rent_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("available_from", models.DateField(blank=True, null=True)),
                (
                    "room_type",
                    models.CharField(
                        choices=[
                            ("private", "Private Room"),
                            ("shared", "Shared Room"),
                            ("entire_place", "Entire Place"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                ("total_rooms", models.PositiveSmallIntegerField(default=1)),
                ("available_rooms", models.PositiveSmallIntegerField(default=1)),
                ("amenities", models.JSONField(blank=True, default=list)),
                ("house_rules", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
