# Generated by Django 5.2.7 on 2025-10-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kustay", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="listing_images/",
            ),
        ),
    ]
