# Generated by Django 5.2.7 on 2025-12-30 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kustay", "0008_block_review_unit_details"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="profile",
            name="department",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="faculty",
        ),
        migrations.AddField(
            model_name="profile",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="students", to="kustay.department"
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="faculty",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="kustay.faculty",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("name", "faculty")},
        ),
    ]
